title: "Traveling Puzzle"
description: "Every journey is a puzzle piece. Travel stories, photo journals, and reflections from around the world."
baseurl: "" # leave empty for root domain
url: "https://rachitsingh05.github.io" # use github.io while testing at work

theme: minima

author: Rachit Singh
email: your-email@example.com

github_username: rachitsingh05
twitter_username: yourprofile
instagram_username: yourprofile

plugins:
  - jekyll-feed
  - jekyll-seo-tag
